---
- name: Install and start MySQL 8 on Amazon Linux 2023
  hosts: db_servers
  become: yes
  vars:
    mysql_root_password: "MySecureRootPassword123"

  tasks:
    - name: Install MySQL 8 server
      dnf:
        name: mysql-server
        state: present

    - name: Ensure MySQL is started and enabled
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Set MySQL root password (only if not already set)
      shell: >
        mysqladmin -u root password '{{ mysql_root_password }}'
      args:
        creates: /var/lib/mysql/mysql  # crude check to prevent re-running
      when: "'localhost' in ansible_facts['fqdn']"

    - name: Ensure MySQL is listening on port 3306
      wait_for:
        port: 3306
        state: started
        timeout: 30
