---
- name: Setup server stack
  hosts: all
  become: true
  roles:
    - role: mysql
      vars:
        mysql_version: "8.0"
    - role: openjdk
    - role: tomcat
      vars: 
        tomcat_force_reinstall: false
        tomcat_version: "9.0.98"
    - role: httpd
    - role: php
      vars:
        php_version: "8.4"
        restart_apache_for_php: true
        php_load_info: true
