---
- import_playbook: playbooks/mysql80.yaml
- import_playbook: playbooks/apache.yaml
- import_playbook: playbooks/php74.yaml
- import_playbook: playbooks/openjdk11.yaml
- import_playbook: playbooks/tomcat9.yaml