---
- name: Preflight checks for all roles
  hosts: all
  gather_facts: false
  become: true
  vars_files:
    - shared-vars.yml
  roles:
    - role: manifest
    - role: preflight

- name: Setup server stack
  hosts: all
  become: true
  vars_files:
    - shared-vars.yml
  roles:
    - role: mysql
    - role: tomcat
    - role: apache
    - role: php
