#!/bin/bash

github_repo="https://github.com/hayeseoin/ansible-lamp.git"
repo_location="/opt/ansible-deployment"

set -euxo pipefail

# Uncomment below blocks if you need an ec2-user password
# # --- User setup ---
# USERNAME="ec2-user"
# PASSWORD="password"  # Change this to something secure!

# # Create the user if not exists
# if ! id "$USERNAME" &>/dev/null; then
#   useradd -m -s /bin/bash "$USERNAME"
#   echo "$USERNAME:$PASSWORD" | chpasswd
#   usermod -aG wheel "$USERNAME"
# fi

# # Allow passwordless sudo
# echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME
# chmod 440 /etc/sudoers.d/$USERNAME

# # --- SSH password auth ---
# sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
# sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
# systemctl restart sshd

# --- Install Python (required by Ansible) and Ansible ---
dnf install -y python3 python3-pip git
ln -s /usr/bin/python3 /usr/bin/python

# Create and activate Python virtual environment
python3 -m venv /opt/ansible-venv
source /opt/ansible-venv/bin/activate

# pip3 install --upgrade pip
pip3 install ansible

# Optional: clean up
dnf clean all

cd /opt
git clone $github_repo $repo_location

echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzwfyTwKohCMQOe8Ah5qdqYwkzLgdV15dne+Dq/iqSBvy00pPyz3uX/LWT73wEU3/YV9KmZN6qr2HsINCjW06cpn/vTBh56pSTzNmesdHgtYV97WOwMxLdlsBnJT81vNoUj7t/hZpgdGuNEJ4uiM6wY+LH7qYf1CAY9i0U3NLtmuS9ryA/MMiDOHeR5GX23ibmbdxAWy791PAVTl1z1Qt7d64vOv1ACoAR4nSGB0sGOvMUH5q9pqhNpw0OrndLbU6ur8of2PrBT6FNYK5ldcRz1ZaalEfRd/ntauGxC29BXGkuHFDY001RtlvUVcRwTdY76LxIjtw7VafC6Vlw6EYLtXAviYmIjrR0XtomkLwc97xzsZ5IF5ENNSt4QlC2N+heLVzGZEo8J2VaMKuxCIOIAn9Bsf+OyHDlP6RLs/E9pMcqNPMnLggMFIuVZ0LZOS2x1AmhG9QaXyDxbui0HsNqZQDmfm2pC325Fyxu/ZvV9D4NPjCtCyGw+crGpVTElSc= eoinh@wsl-debian' >> /home/ec2-user/authorized_keys
