#!/bin/bash

github_repo="https://github.com/hayeseoin/ansible-lamp.git"
repo_location="/opt/ansible-deployment"

set -euxo pipefail

# Uncomment below blocks if you need an ec2-user password
# # --- User setup ---
# USERNAME="ec2-user"
# PASSWORD="password"  # Change this to something secure!

# # Create the user if not exists
# if ! id "$USERNAME" &>/dev/null; then
#   useradd -m -s /bin/bash "$USERNAME"
#   echo "$USERNAME:$PASSWORD" | chpasswd
#   usermod -aG wheel "$USERNAME"
# fi

# # Allow passwordless sudo
# echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME
# chmod 440 /etc/sudoers.d/$USERNAME

# # --- SSH password auth ---
# sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
# sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
# systemctl restart sshd

# --- Install Python (required by Ansible) and Ansible ---
dnf install -y python3 python3-pip git
ln -s /usr/bin/python3 /usr/bin/python

# Create and activate Python virtual environment
python3 -m venv /opt/ansible-venv
source /opt/ansible-venv/bin/activate

# pip3 install --upgrade pip
pip3 install ansible

# Optional: clean up
dnf clean all

cd /opt
git clone $github_repo $repo_location

source /opt/ansible-venv/bin/activate
ansible-playbook -i "localhost," -c local /opt/ansible-deployment/mysql8.yaml
touch /root/ansible-complete