---
- name: Create temp install directory
  file:
    path: "{{ mysql_install_dir }}"
    state: directory
    mode: '0644'

- name: Copy MySQL 8.0 repo RPM to target
  copy:
    src: mysql84-community-release-el9-1.noarch.rpm
    dest: "{{ mysql_install_dir }}/mysql84-community-release-el9-1.noarch.rpm"
    mode: '0644'

- name: Install MySQL 8.4 community release RPM
  dnf:
    disable_gpg_check: true
    name: "{{ mysql_install_dir }}/mysql84-community-release-el9-1.noarch.rpm"
    state: present

- name: Install MySQL 8.0 
  dnf:
    disablerepo:
      - mysql-8.4-lts-community
      - mysql-tools-8.4-lts-community
    enablerepo:
      - mysql80-community
      - mysql-tools-community
    name:
      - mysql-community-server
    state: latest

- name: Enable and start MySQL service
  service:
    name: mysqld
    enabled: yes
    state: started

- name: Copy MySQL root password script to target
  copy:
    src: mysql_root_pw.sh
    dest: "{{ mysql_install_dir }}/mysql_root_pw.sh"
    mode: '0755'

- name: Run MySQL root password script
  shell: "{{ mysql_install_dir }}/mysql_root_pw.sh"