- name: Check if PHP 7.4 is installed
  stat:
    path: /usr/local/php-7.4/bin/php
  register: php74_stat

- set_fact:
    php74_installed: "{{ php74_stat.stat.exists }}"

- name: Copy PHP install assets
  become: true
  copy:
    src: php74-fpm.service
    dest: /tmp/php_install/
    mode: '0644'
  when: php_version == "7.4"

- name: Install PHP 7.4 if requested
  become: true
  shell: install.sh
  args:
    creates: /usr/local/php-7.4/bin/php
    chdir: "{{ php_install_dir }}"
  environment:
    PHP_DOWNLOAD_LINK: "{{ php_download_link }}"
  when: php_version == "7.4"

# - name: Download uninstall script
#   become: true
#   copy:
#     src: uninstall.sh
#     dest: /tmp/php_install/
#     mode: '0755'
#   when: 
#     - php_version != "7.4"
#     - php74_installed

- name: Uninstall PHP 7.4 if switching to another version
  shell: "{{ role_path }}/files/uninstall.sh"
  when:
    - php_version != "7.4"
    - php74_installed

- name: Install PHP 8.x via DNF
  dnf:
    name: php
    state: present
  when: php_version is version('8.0', '>=')
