- name: Check if PHP 7.4 is installed
  stat:
    path: /usr/local/php-7.4/bin/php
  register: php74_stat

- set_fact:
    php74_installed: "{{ php74_stat.stat.exists }}"

- name: Install PHP 7.4 if requested
  command: "{{ role_path }}/files/install.sh"
  args:
    creates: /usr/local/php-7.4/bin/php
  when: php_version == "7.4"

- name: Uninstall PHP 7.4 if switching to another version
  command: "{{ role_path }}/files/uninstall.sh"
  when:
    - php_version != "7.4"
    - php74_installed

- name: Install PHP 8.x via DNF
  dnf:
    name: php
    state: present
  when: php_version is version('8.0', '>=')
