- name: Download uninstall script
  copy:
    src: uninstall.sh
    dest: "{{ php_install_dir}}/uninstall.sh"
    mode: '0755'
  when: 
    - php74_installed

- name: Uninstall PHP 7.4 if switching to another version
  shell: " {{ php_install_dir }}/uninstall.sh"
  when:
    - php74_installed

- name: Install PHP 8.x via DNF
  dnf:
    name: php
    state: present