---
- name: Create temp install directory
  file:
    path: "{{ tomcat_temp_install }}"
    state: directory
    mode: '0644'

- name: Create tomcat group
  group:
    name: tomcat

- name: Create tomcat user
  user:
    name: tomcat
    group: tomcat
    home: /home/tomcat
    shell: /bin/false
    create_home: no

- name: Create installation directory
  file:
    path: "{{tomcat_install_dir}}"
    state: directory
    owner: tomcat
    group: tomcat
    mode: '0755'

- name: Download Tomcat archive
  get_url:
    url: "{{ tomcat_download_url }}"
    dest: "{{ tomcat_temp_install}}/{{ tomcat_tarball }}"
    mode: '0644'

- name: Extract Tomcat
  shell: "tar -zxf {{ tomcat_temp_install}}/{{ tomcat_tarball }} -C {{tomcat_install_dir}}/"

- name: Symlink current to latest version
  file:
    src: "{{tomcat_install_dir}}/{{ tomcat_name}}"
    dest: "{{tomcat_symlink}}"
    state: link

- name: Change ownership
  file:
    path: "{{tomcat_symlink}}"
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

- name: Add tomcat9 service file
  copy:
    src: tomcat9.service
    dest: /etc/systemd/system/tomcat9.service

- name: Enable and start Tomcat
  systemd:
    name: tomcat9
    enabled: yes
    state: started
