---
- name: Install OpenJDK 11 manually on RHEL
  hosts: all
  become: yes
  vars:
    jdk_url: "https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.27%2B6/OpenJDK11U-jdk_x64_linux_hotspot_11.0.27_6.tar.gz"
    jdk_tarball: "jdk-11.0.27+6"
    jdk_install_dir: "/usr/lib/jvm"
    jdk_folder_name: "11.0.27_6"

  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ jdk_install_dir }}"
        state: directory
        mode: '0755'

    - name: Download OpenJDK 11 tarball
      get_url:
        url: "{{ jdk_url }}"
        dest: /tmp/OpenJDK11U-jdk_x64_linux_hotspot_11.0.27_6.tar.gz
        mode: '0644'
      register: download_result

    - name: Extract OpenJDK to target directory
      shell: tar -xf /tmp/OpenJDK11U-jdk_x64_linux_hotspot_11.0.27_6.tar.gz -C /usr/lib/jvm/
      # creates: "{{ jdk_install_dir }}/{{ jdk_folder_name }}"

    - name: Create symlinks for java binaries
      file:
        src: /usr/lib/jvm/jdk-11.0.27+6/bin/java
        dest: /opt/java
        state: link
        force: yes

    - name: Set JAVA_HOME system-wide (optional)
      copy:
        dest: /etc/profile.d/java.sh
        mode: '0644'
        content: |
          export JAVA_HOME=/opt/java/
          export PATH=\$JAVA_HOME/bin:\$PATH