---
- name: Install PHP 7.4 (custom)
  hosts: localhost
  become: true

  tasks:

    - name: Ensure required packages are installed
      dnf:
        name:
          - libicu
          - libxslt
          - oniguruma
          - libedit
          - libuuid
          - tar
          - wget
        state: present

    - name: Extract custom PHP tarball
      shell: tar -xvf files/php-7.4.tar.gz -C /usr/local/

    - name: Create symlinks for PHP binaries
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: yes
      loop:
        - { src: '/usr/local/php-7.4/bin/php', dest: '/usr/bin/php' }
        - { src: '/usr/local/php-7.4/bin/phpize', dest: '/usr/bin/phpize' }
        - { src: '/usr/local/php-7.4/bin/php-config', dest: '/usr/bin/php-config' }

    - name: Copy PHP-FPM systemd service file
      copy:
        src: php74-fpm.service
        dest: /etc/systemd/system/php-fpm.service

    - name: Reload systemd and enable PHP-FPM
      systemd:
        daemon_reload: yes
        name: php-fpm.service
        enabled: yes
        state: started

    - name: Produce
      copy:
        src: php74-fpm.conf
        dest: /etc/httpd/conf.d/php74-fpm.conf
